#!/usr/bin/env python

import argparse
import sys

from os import environ
from pathlib import Path


def main():
    args = parse_args()
    config_file = "config" if args.config == "." else f"config.{args.config}"
    config_path = Path(environ["HOME"]).joinpath(f".kube/{config_file}")
    if not config_path.exists():
        sys.exit(f"Config file not found: {config_path}")

    print(f"Using config file: {config_path}", file=sys.stderr)
    print(f"export KUBECONFIG='{config_path}'")

def parse_args():
    parser = argparse.ArgumentParser(description="Switch current kube config file")

    parser.add_argument(
        "config",
        type=str,
        help="The suffix of the config file to use. Specify . to use the default config file",
    )

    return parser.parse_args()


main()
